services:
  todolist:
    build:
      context: ./server
    ports: 
      - "3000:3000"
  todolist-client:
    build:
      context: ./client
    ports:
      - "3006:3000"
    depends_on:
      - todolist

    
